// flow-typed signature: cb8ab545afcce918476f3cc671a34243
// flow-typed version: <<STUB>>/babel-plugin-polished_v^1.0.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-polished'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-polished' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-polished/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-polished/test/fixtures/namespace/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-polished/test/fixtures/namespace/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-polished/test/fixtures/nested-paths/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-polished/test/fixtures/nested-paths/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-polished/test/fixtures/non-literal-arg/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-polished/test/fixtures/non-literal-arg/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-polished/test/fixtures/specifiers/actual' {
  declare module.exports: any;
}

declare module 'babel-plugin-polished/test/fixtures/specifiers/expected' {
  declare module.exports: any;
}

declare module 'babel-plugin-polished/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-polished/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-polished/lib/index'>;
}
declare module 'babel-plugin-polished/test/fixtures/namespace/actual.js' {
  declare module.exports: $Exports<'babel-plugin-polished/test/fixtures/namespace/actual'>;
}
declare module 'babel-plugin-polished/test/fixtures/namespace/expected.js' {
  declare module.exports: $Exports<'babel-plugin-polished/test/fixtures/namespace/expected'>;
}
declare module 'babel-plugin-polished/test/fixtures/nested-paths/actual.js' {
  declare module.exports: $Exports<'babel-plugin-polished/test/fixtures/nested-paths/actual'>;
}
declare module 'babel-plugin-polished/test/fixtures/nested-paths/expected.js' {
  declare module.exports: $Exports<'babel-plugin-polished/test/fixtures/nested-paths/expected'>;
}
declare module 'babel-plugin-polished/test/fixtures/non-literal-arg/actual.js' {
  declare module.exports: $Exports<'babel-plugin-polished/test/fixtures/non-literal-arg/actual'>;
}
declare module 'babel-plugin-polished/test/fixtures/non-literal-arg/expected.js' {
  declare module.exports: $Exports<'babel-plugin-polished/test/fixtures/non-literal-arg/expected'>;
}
declare module 'babel-plugin-polished/test/fixtures/specifiers/actual.js' {
  declare module.exports: $Exports<'babel-plugin-polished/test/fixtures/specifiers/actual'>;
}
declare module 'babel-plugin-polished/test/fixtures/specifiers/expected.js' {
  declare module.exports: $Exports<'babel-plugin-polished/test/fixtures/specifiers/expected'>;
}
declare module 'babel-plugin-polished/test/index.js' {
  declare module.exports: $Exports<'babel-plugin-polished/test/index'>;
}
