// flow-typed signature: 8a0b82d0e1d75957d60ca747f686a480
// flow-typed version: <<STUB>>/node-plop_v0.5.4/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-plop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-plop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-plop/lib/index' {
  declare module.exports: any;
}

declare module 'node-plop/lib/modules/baked-in-helpers' {
  declare module.exports: any;
}

declare module 'node-plop/lib/modules/fs-promise-proxy' {
  declare module.exports: any;
}

declare module 'node-plop/lib/modules/generator-runner' {
  declare module.exports: any;
}

declare module 'node-plop/lib/modules/node-plop' {
  declare module.exports: any;
}

declare module 'node-plop/plop-templates/ava-test' {
  declare module.exports: any;
}

declare module 'node-plop/plopfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-plop/lib/index.js' {
  declare module.exports: $Exports<'node-plop/lib/index'>;
}
declare module 'node-plop/lib/modules/baked-in-helpers.js' {
  declare module.exports: $Exports<'node-plop/lib/modules/baked-in-helpers'>;
}
declare module 'node-plop/lib/modules/fs-promise-proxy.js' {
  declare module.exports: $Exports<'node-plop/lib/modules/fs-promise-proxy'>;
}
declare module 'node-plop/lib/modules/generator-runner.js' {
  declare module.exports: $Exports<'node-plop/lib/modules/generator-runner'>;
}
declare module 'node-plop/lib/modules/node-plop.js' {
  declare module.exports: $Exports<'node-plop/lib/modules/node-plop'>;
}
declare module 'node-plop/plop-templates/ava-test.js' {
  declare module.exports: $Exports<'node-plop/plop-templates/ava-test'>;
}
declare module 'node-plop/plopfile.js' {
  declare module.exports: $Exports<'node-plop/plopfile'>;
}
