// flow-typed signature: 4bc75bbf8fc5a991fed8ec39074fc1e6
// flow-typed version: <<STUB>>/optipng-bin_v^3.1.4/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optipng-bin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'optipng-bin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'optipng-bin/cli' {
  declare module.exports: any;
}

declare module 'optipng-bin/lib/index' {
  declare module.exports: any;
}

declare module 'optipng-bin/lib/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'optipng-bin/cli.js' {
  declare module.exports: $Exports<'optipng-bin/cli'>;
}
declare module 'optipng-bin/index' {
  declare module.exports: $Exports<'optipng-bin'>;
}
declare module 'optipng-bin/index.js' {
  declare module.exports: $Exports<'optipng-bin'>;
}
declare module 'optipng-bin/lib/index.js' {
  declare module.exports: $Exports<'optipng-bin/lib/index'>;
}
declare module 'optipng-bin/lib/install.js' {
  declare module.exports: $Exports<'optipng-bin/lib/install'>;
}
