// flow-typed signature: 7237fa37df54fed719ce93ae3c969b18
// flow-typed version: <<STUB>>/pngquant-bin_v^3.1.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pngquant-bin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pngquant-bin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pngquant-bin/cli' {
  declare module.exports: any;
}

declare module 'pngquant-bin/lib/index' {
  declare module.exports: any;
}

declare module 'pngquant-bin/lib/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pngquant-bin/cli.js' {
  declare module.exports: $Exports<'pngquant-bin/cli'>;
}
declare module 'pngquant-bin/index' {
  declare module.exports: $Exports<'pngquant-bin'>;
}
declare module 'pngquant-bin/index.js' {
  declare module.exports: $Exports<'pngquant-bin'>;
}
declare module 'pngquant-bin/lib/index.js' {
  declare module.exports: $Exports<'pngquant-bin/lib/index'>;
}
declare module 'pngquant-bin/lib/install.js' {
  declare module.exports: $Exports<'pngquant-bin/lib/install'>;
}
